version: '3.6'

services:

  django:
    build: .
    image: django-flutterwave
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./example/env/dev.env