# Generated by Django 3.1.4 on 2020-12-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflutterwave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flwplanmodel',
            name='interval',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi Annually'), ('yearly', 'Yearly')], help_text='Payment frequency. Only required if this is a subscription plan.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='flwtransactionmodel',
            name='created_at',
            field=models.DateTimeField(help_text='Created datetime received from Flutterwave'),
        ),
    ]
