# Generated by Django 3.1.4 on 2020-12-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflutterwave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flwplanmodel',
            name='interval',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi Annually'), ('yearly', 'Yearly')], default='monthly', help_text='Payment frequency', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flwtransactionmodel',
            name='created_at',
            field=models.DateTimeField(help_text='Created datetime received from Flutterwave'),
        ),
    ]
