# Generated by Django 2.2.3 on 2019-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onceoffmodel',
            name='description',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='description',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
